### Learning NumPy!

Numpy Documantation: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

**Very Baisc Stuffs of Arrays in NumPy**

In [1]:
import numpy as np

In [2]:
simpleArr = np.array([56, 67, 21, 88, 8])

simpleArr[simpleArr.shape[0]-2]  # ajaira pechal ;-)

88

In [3]:
myArr = np.array([[22, 34], [90, 45], [89, 5]], np.int8)
myArr

array([[22, 34],
       [90, 45],
       [89,  5]], dtype=int8)

In [4]:
myArr.dtype  # data type the array elements

dtype('int8')

In [5]:
myArr[2, 1]  # accessing the element of 3rd row 2nd column

5

In [6]:
myArr.shape  # shape of the array

(3, 2)

In [7]:
myArr.size  # returns the total number of array elements

6

***# array with objects as elements***

In [8]:
obArray = np.array({56, 89, 56})  
# not recomended => reduces efficiency...!
obArray

array({56, 89}, dtype=object)

***# Intrinsic numpy array creation objects***

**1. Zeros as elements**

In [9]:
zeros = np.zeros((2, 4), np.int8)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

**2. Range array**

In [10]:
array_size = 30
rng = np.arange(array_size)  # returns an x size of array
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

**3. Linearly / equally spaced array elements**

In [11]:
strt_point = 1  # starting point
end_point = 50 # ending point
elemnt_num = 10 # required number of elements in the array

lnspace = np.linspace(strt_point, end_point, elemnt_num)
lnspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

**4. Empty Array *i.e. array with random values/elements***

In [12]:
x = 4  # required number of rows
y = 6  # required number of columns / elements-per-row
emp = np.empty((x, y))
emp

array([[3.56043053e-307, 1.37961641e-306, 1.37962320e-306,
        1.78019354e-306, 1.33508845e-306, 1.33511969e-306],
       [1.24610383e-306, 1.69118108e-306, 8.06632139e-308,
        1.20160711e-306, 1.69119330e-306, 1.29062229e-306],
       [1.60217812e-306, 1.37961370e-306, 1.42417629e-306,
        1.11258277e-307, 1.05700515e-307, 1.11261774e-306],
       [1.29060871e-306, 8.34424766e-308, 8.34445138e-308,
        1.37959129e-306, 1.02360528e-306, 1.14469050e+243]])

**4.1. Empty_like**

In [13]:
# creates an empty array which is equally sized & similer to an exsiting array
# And the values will be random values like the empty array
emp_like = np.empty_like(myArr)
emp_like

array([[-112, -128],
       [ -22, -122],
       [   3,    2]], dtype=int8)

**5. Identity array**

In [14]:
ide = np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**Other Important Methods:**

In [15]:
# reshaping an array
row_num = 5
element_num = 6
# rng array has 30 elements => row_num * element = 30; this is a must match
rng = rng.reshape(row_num, element_num)
rng  # Now rng array has reshaped

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [16]:
# ravel method : turn any array into a 1D array
emp  = emp.ravel()
emp

array([3.56043053e-307, 1.37961641e-306, 1.37962320e-306, 1.78019354e-306,
       1.33508845e-306, 1.33511969e-306, 1.24610383e-306, 1.69118108e-306,
       8.06632139e-308, 1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
       1.60217812e-306, 1.37961370e-306, 1.42417629e-306, 1.11258277e-307,
       1.05700515e-307, 1.11261774e-306, 1.29060871e-306, 8.34424766e-308,
       8.34445138e-308, 1.37959129e-306, 1.02360528e-306, 1.14469050e+243])

**Axises in Array & their various funtionalities *(i.e. Matirx like vehaviour)***

In [17]:
# Let's define a 2D-array / vector-matrix
vec = [[23, 78, 90],
       [45, 76, 23],
       [45, 12, 95]]
np_vec = np.array(vec)
np_vec

array([[23, 78, 90],
       [45, 76, 23],
       [45, 12, 95]])

**>> Sum of Columns / Rows:**

In [18]:
col_tot = np_vec.sum(axis=0)  # Sum of columns
print("Columns Total:\t", col_tot)
row_tot = np_vec.sum(axis=1) # Sum of rows
print("Rows Total: \t", row_tot)

Columns Total:	 [113 166 208]
Rows Total: 	 [191 144 152]


**Note:** *In 2D array, columns are axis=0 & rows are axis=1* 

*But, In 1D array, there is only One axis (axis=0)*

**> Transpose Array:**

In [19]:
np_vec.T

array([[23, 45, 45],
       [78, 76, 12],
       [90, 23, 95]])

**> Flat attribute / iterator**

In [20]:
elements = np_vec.flat 
# It's basically an array of all elements of the 2D array(i.e. it's a iterator)
for e in elements:
    print(e, end=" ")

23 78 90 45 76 23 45 12 95 

**> Other Very Important Attributes / Methods:**

In [21]:
# Dimension of the array:
np_vec.ndim # Here: it answers 2 as it's an 2D array

2

In [22]:
# Total size of the array IN BYTES
np_vec.nbytes

36

In [23]:
# Index of the BIGGEST element of the array
max_ele_indx = np_vec.argmax()

max_num = elements[max_ele_indx]  # "elements" is the iterator of "np_vec"
print("Max Num: \t", max_num)

# Do it by Axises:
cols_max = np_vec.argmax(axis=0)
print("Max in Columns: ", cols_max)
rows_max = np_vec.argmax(axis=1)
print("Max in Rows: \t", rows_max)

Max Num: 	 95
Max in Columns:  [1 0 2]
Max in Rows: 	 [2 1 2]


In [24]:
# Index of the SMALLEST element of the array
min_ele_indx = np_vec.argmin()

elements[min_ele_indx]  # "elements" is the iterator of "np_vec"

# Do it by Axises: **similar to the .argmax()

12

In [25]:
# returns Indexes of the SORTED elements
srtd_np_vec = np_vec.argsort()
# Note, in 2D array, the method sorts the array row by row (not the full array)

row_srtd_np_vec = np_vec.argsort(axis=1)  # equals to the default sorted vec ^
col_srtd_np_vec = np_vec.argsort(axis=0)

print("Main array:\n", np_vec)
print("Sorted indexes (Default):\n", srtd_np_vec)
print("Sorted indexes(rows):\n", row_srtd_np_vec)
print("Sorted indexes (columns):\n", col_srtd_np_vec)

# elements.argsort() error: 'numpy.flatiter' object has no attribute 'argsort'

Main array:
 [[23 78 90]
 [45 76 23]
 [45 12 95]]
Sorted indexes (Default):
 [[0 1 2]
 [2 0 1]
 [1 0 2]]
Sorted indexes(rows):
 [[0 1 2]
 [2 0 1]
 [1 0 2]]
Sorted indexes (columns):
 [[0 2 1]
 [1 1 0]
 [2 0 2]]


***Arithmatirc Operations in numpy arrays:***
Power of normal Matrix

In [26]:
np_vec1 = np.array([[27, -28, -40],
                  [5, -26, 27],
                  [5, 38, -45]])

In [27]:
# addition of arrays
add_vec = np_vec + np_vec1
add_vec

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [28]:
# multiplication of arrays
mul_vec = np_vec * np_vec1
mul_vec

array([[  621, -2184, -3600],
       [  225, -1976,   621],
       [  225,   456, -4275]])

In [29]:
div_vec = np_vec / np_vec1
print("Full Divition:\n", div_vec)

rmn_div_vec = np_vec // np_vec1
print("Integral Divition:\n", rmn_div_vec)

Full Divition:
 [[ 0.85185185 -2.78571429 -2.25      ]
 [ 9.         -2.92307692  0.85185185]
 [ 9.          0.31578947 -2.11111111]]
Integral Divition:
 [[ 0 -3 -3]
 [ 9 -3  0]
 [ 9  0 -3]]


In [30]:
# squar root of array
sqrt_vec = np.sqrt(np_vec)
sqrt_vec

array([[4.79583152, 8.83176087, 9.48683298],
       [6.70820393, 8.71779789, 4.79583152],
       [6.70820393, 3.46410162, 9.74679434]])

In [31]:
# sum of all elements of single array
np_vec.sum()

487

In [32]:
# max / min element of an array
np_vec.max()
np_vec.min()

12

In [33]:
# searching element with condition

special_array = np.where(np_vec > 50)
special_array

# output: (array([0, 0, 1, 2], dtype=int64), array([1, 2, 1, 2], dtype=int64))
# explanation: (row, column)
#         0,1 => first element
#         0,2 => second element
#         1,1 => third element
#         2,2 => fourth element

(array([0, 0, 1, 2], dtype=int64), array([1, 2, 1, 2], dtype=int64))

In [34]:
# non-zero elements in array

np.count_nonzero(np_vec) # number of Non-zero elements

np.nonzero(np_vec)  # position of non-zero elements
# each touple defines each axis

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))